---
# This Ansible Playbook will the necessary changes to the containerD runtime engine present in RKE2 in order to support the NVIDIA K8 Device Driver.
- hosts: all

  tasks:

  - name: verify RKE2 is installed where we expect
    stat:
      path: /var/lib/rancher/rke2
    register: dir_details

  - debug:
      msg: "RKE2 Dir Present"
  when: dir_details.stat.exists and dir_details.stat.isdir

  - name: Create containerD folder if it doesn't exist
    file:
      path: /var/lib/rancher/rke2/agent/etc/containerd/
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: create config.toml.tmpl file for containerD
    copy:
      src: /template/config.toml.tmpl
      dest: /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl
      owner: root
      group: root
      mode: '0755'

  - name: Check state of services
    service_facts:
    register: service_state

  - name: Restart rke2-server + associated services
    service:
      name: "{{ item }}"
      state: restarted
      daemon_reload: yes
    with_items:
      - 'rke2-server'
      - 'containerd'
    when: service_state.ansible_facts.services["rke2-server.service"].state == 'started'
 
  - name: Restart rke2-agent + associated services
    service:
      name: "{{ item }}"
      state: restarted
      daemon_reload: yes
    with_items:
      - 'rke2-agent'
      - 'containerd'
    when: service_state.ansible_facts.services["rke2-agent.service"].state == 'started'